import { Metadata } from "next";
import { Suspense } from "react";
// export const metadata: Metadata = {
//   title: "Product",
//   description: "Generated by create next app",
// };
export async function generateMetadata({
  params,
}: {
  params: { productId: string };
}) {
  const promise2 = await fetch("https://jsonplaceholder.typicode.com/users");

  const usersdata = await promise2.json();
  return {
    title: {
      absolute: `product ${params.productId} `,
    },
  };
}
const Page = async ({ params }: { params: { productId: number } }) => {
  const { productId } = params;

  const promise1 = new Promise((resolve) =>
    setTimeout(() => resolve("i am resolved"), 5000)
  );

  const promise2 = await fetch("https://jsonplaceholder.typicode.com/users");

  const usersdata = await promise2.json();

  return (
    <div>
      This is product {productId}
      <br></br>
      <br></br>
      <br></br>
      <Suspense fallback="Data is loading...">
        <Component2 Promise={promise1} />
      </Suspense>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      {JSON.stringify(usersdata)}
    </div>
  );
};

export default Page;

const Component2 = async ({ Promise }: { Promise: Promise<unknown> }) => {
  const data = await Promise;
  return <div>{JSON.stringify(data)}</div>;
};
